/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.funcionarioGUI;

import view.produtoGUI.*;
import control.ControleFuncionario;
import control.ControleGerente;
import javax.swing.JOptionPane;
import model.Funcionario;
import model.Produto;
import view.JfControleFuncionario;
import view.JfControleProduto;
import view.JfPainelSelecaoControles;

/**
 *
 * @author Lenovo
 */
public class JfAlterarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JfAlterarProduto
     */
    public JfAlterarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JbRetornar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JtfMatriculaFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JtfNomeFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfEnderecoFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JtfSalarioFuncionario = new javax.swing.JTextField();
        JbAlterarFunionario = new javax.swing.JButton();
        JpfSenhaFuncionario = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        JtfTelefoneFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Alterar Funcionário");

        JbRetornar.setForeground(new java.awt.Color(255, 0, 0));
        JbRetornar.setText("Retornar");
        JbRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRetornarActionPerformed(evt);
            }
        });

        jLabel2.setText("Matrícula");

        jLabel3.setText("Nome");

        JtfNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeFuncionarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha");

        jLabel5.setText("Endereço (Cidade/Estado):");

        jLabel6.setText("Salario (xxxx.xx)");

        JbAlterarFunionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbAlterarFunionario.setText("Alterar");
        JbAlterarFunionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarFunionarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefone:");

        JtfTelefoneFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTelefoneFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbRetornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(JbAlterarFunionario)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jtfEnderecoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(JtfSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JtfMatriculaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(JtfNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(JpfSenhaFuncionario)
                    .addComponent(JtfTelefoneFuncionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbRetornar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpfSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JtfTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbAlterarFunionario)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeFuncionarioActionPerformed

    private void JbAlterarFunionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarFunionarioActionPerformed
        String matriculaFuncionarioString = JtfMatriculaFuncionario.getText();
        String salarioFuncionarioString = JtfSalarioFuncionario.getText();
        String telefoneFuncionario = JtfTelefoneFuncionario.getText();
        String nomeFuncionario = JtfNomeFuncionario.getText();
        String enderecoFuncionario = jtfEnderecoFuncionario.getText();
        String senhaFuncionario = JpfSenhaFuncionario.getText();
        ControleGerente manGerente = null;    
        Funcionario manFuncionario = null;
        
         boolean camposPreenchidos = !(matriculaFuncionarioString.isEmpty() || salarioFuncionarioString.isEmpty() || telefoneFuncionario.isEmpty() || nomeFuncionario.isEmpty() || enderecoFuncionario.isEmpty());
        if (camposPreenchidos) {
            int matriculaFuncionario = Integer.parseInt(matriculaFuncionarioString);
            Float salarioFuncionario = Float.parseFloat(salarioFuncionarioString);
            
            manFuncionario = new Funcionario(matriculaFuncionario, nomeFuncionario, enderecoFuncionario,telefoneFuncionario, salarioFuncionario, senhaFuncionario);
            manGerente = new ControleGerente();
            if(manGerente.getFuncionarioById(matriculaFuncionario) != null){
                manGerente.updateFuncionario(manFuncionario); 
            }else{
                JOptionPane.showMessageDialog(null, "Identificador não encontrado, verifique os dados e tente novamente.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para cadastrar");
        }
    }//GEN-LAST:event_JbAlterarFunionarioActionPerformed

    private void JbRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRetornarActionPerformed
        JfControleFuncionario jfControleFuncionario = new JfControleFuncionario();
        jfControleFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbRetornarActionPerformed

    private void JtfTelefoneFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTelefoneFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTelefoneFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfAlterarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAlterarFunionario;
    private javax.swing.JButton JbRetornar;
    private javax.swing.JPasswordField JpfSenhaFuncionario;
    private javax.swing.JTextField JtfMatriculaFuncionario;
    private javax.swing.JTextField JtfNomeFuncionario;
    private javax.swing.JTextField JtfSalarioFuncionario;
    private javax.swing.JTextField JtfTelefoneFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtfEnderecoFuncionario;
    // End of variables declaration//GEN-END:variables
}
