/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.funcionarioGUI;

import view.produtoGUI.*;
import control.ControleFuncionario;
import control.ControleGerente;
import javax.swing.JOptionPane;
import model.Produto;
import view.JfControleFuncionario;
import view.JfControleProduto;

/**
 *
 * @author Lenovo
 */
public class JfSelecionarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JfSelecionarProduto
     */
    public JfSelecionarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtfMatriculaFuncionario = new javax.swing.JTextField();
        JbRetornar = new javax.swing.JButton();
        JbSelecionarFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Selecionar Funcionário");

        jLabel2.setText("Matrícula");

        JtfMatriculaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfMatriculaFuncionarioActionPerformed(evt);
            }
        });

        JbRetornar.setForeground(new java.awt.Color(255, 0, 0));
        JbRetornar.setText("Retornar");
        JbRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRetornarActionPerformed(evt);
            }
        });

        JbSelecionarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbSelecionarFuncionario.setText("Selecionar");
        JbSelecionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSelecionarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbRetornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbSelecionarFuncionario)
                    .addComponent(jLabel2)
                    .addComponent(JtfMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JbRetornar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbSelecionarFuncionario)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfMatriculaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfMatriculaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfMatriculaFuncionarioActionPerformed

    private void JbRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRetornarActionPerformed
        JfControleFuncionario jfControleFuncionario = new JfControleFuncionario();
        jfControleFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbRetornarActionPerformed

    private void JbSelecionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSelecionarFuncionarioActionPerformed
        String matriculaFuncionarioString = JtfMatriculaFuncionario.getText();
        ControleGerente manGerente = new ControleGerente();
        
        boolean camposPreenchidos = !(matriculaFuncionarioString.isEmpty());
        if (camposPreenchidos) {
            int MatrincuaFuncionario = Integer.parseInt(matriculaFuncionarioString);
            if(manGerente.getFuncionarioById(MatrincuaFuncionario) != null){
                String mensagemSucesso = "Funcionario: " + manGerente.getFuncionarioById(MatrincuaFuncionario).describeFuncionario() + "\nAcessado com sucesso";
            JOptionPane.showMessageDialog(null, mensagemSucesso);                 
            } else {
                JOptionPane.showMessageDialog(null, "Identificador não encontrado, verifique os dados e tente novamente.");
            }  
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para Selecionar.");
        }
    }//GEN-LAST:event_JbSelecionarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfSelecionarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbRetornar;
    private javax.swing.JButton JbSelecionarFuncionario;
    private javax.swing.JTextField JtfMatriculaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
