/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.funcionarioGUI.JfAlterarFuncionario;
import view.funcionarioGUI.JfCadastrarFuncionario;
import view.funcionarioGUI.JfDeletarFuncionario;
import view.funcionarioGUI.JfSelecionarFuncionario;
import view.produtoGUI.*;

/**
 *
 * @author Lenovo
 */
public class JfControleFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ControleProdutoGUI
     */
    public JfControleFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JbCadastrarFuncionario = new javax.swing.JButton();
        JbSelecionarFuncionario = new javax.swing.JButton();
        JbAlterarFuncionario = new javax.swing.JButton();
        JbDeletarFuncionario = new javax.swing.JButton();
        JbRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Controle Funcionario");

        JbCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbCadastrarFuncionario.setText("Cadastrar");
        JbCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarFuncionarioActionPerformed(evt);
            }
        });

        JbSelecionarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbSelecionarFuncionario.setText("Selecionar ");
        JbSelecionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSelecionarFuncionarioActionPerformed(evt);
            }
        });

        JbAlterarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbAlterarFuncionario.setText("Alterar");
        JbAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarFuncionarioActionPerformed(evt);
            }
        });

        JbDeletarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbDeletarFuncionario.setText("Deletar");
        JbDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDeletarFuncionarioActionPerformed(evt);
            }
        });

        JbRetornar.setForeground(new java.awt.Color(255, 0, 0));
        JbRetornar.setText("Retornar");
        JbRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JbRetornar)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JbCadastrarFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(JbAlterarFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(JbSelecionarFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(JbDeletarFuncionario)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JbRetornar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbDeletarFuncionario)
                    .addComponent(JbSelecionarFuncionario)
                    .addComponent(JbAlterarFuncionario)
                    .addComponent(JbCadastrarFuncionario))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarFuncionarioActionPerformed
        JfCadastrarFuncionario JfCadastrarProduto = new JfCadastrarFuncionario();
        JfCadastrarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbCadastrarFuncionarioActionPerformed

    private void JbRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRetornarActionPerformed
        JfPainelSelecaoControles jfPainelControles = new JfPainelSelecaoControles();
        jfPainelControles.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbRetornarActionPerformed

    private void JbAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarFuncionarioActionPerformed
        JfAlterarFuncionario jfAlterarFuncionario = new JfAlterarFuncionario();
        jfAlterarFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbAlterarFuncionarioActionPerformed

    private void JbSelecionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSelecionarFuncionarioActionPerformed
        JfSelecionarFuncionario jfSelecionarFuncionario = new JfSelecionarFuncionario();
        jfSelecionarFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbSelecionarFuncionarioActionPerformed

    private void JbDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDeletarFuncionarioActionPerformed
        JfDeletarFuncionario jfDeletarFuncionario = new JfDeletarFuncionario();
        jfDeletarFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbDeletarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfControleFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAlterarFuncionario;
    private javax.swing.JButton JbCadastrarFuncionario;
    private javax.swing.JButton JbDeletarFuncionario;
    private javax.swing.JButton JbRetornar;
    private javax.swing.JButton JbSelecionarFuncionario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
