/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.funcionarioGUI.JfCadastrarFuncionario;
import view.produtoGUI.*;

/**
 *
 * @author Lenovo
 */
public class JfControleProduto extends javax.swing.JFrame {

    /**
     * Creates new form ControleProdutoGUI
     */
    public JfControleProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JbCadastrarProduto = new javax.swing.JButton();
        JbSelecionarProduto = new javax.swing.JButton();
        JbAlterarProduto = new javax.swing.JButton();
        JbDeletarProduto = new javax.swing.JButton();
        JbRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Controle Produto");

        JbCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbCadastrarProduto.setText("Cadastrar");
        JbCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarProdutoActionPerformed(evt);
            }
        });

        JbSelecionarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbSelecionarProduto.setText("Selecionar ");
        JbSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSelecionarProdutoActionPerformed(evt);
            }
        });

        JbAlterarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbAlterarProduto.setText("Alterar");
        JbAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarProdutoActionPerformed(evt);
            }
        });

        JbDeletarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbDeletarProduto.setText("Deletar");
        JbDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDeletarProdutoActionPerformed(evt);
            }
        });

        JbRetornar.setForeground(new java.awt.Color(255, 0, 0));
        JbRetornar.setText("Retornar");
        JbRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JbRetornar)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JbCadastrarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(JbAlterarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(JbSelecionarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(JbDeletarProduto)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JbRetornar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbDeletarProduto)
                    .addComponent(JbSelecionarProduto)
                    .addComponent(JbAlterarProduto)
                    .addComponent(JbCadastrarProduto))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarProdutoActionPerformed
        JfCadastrarProduto JfCadastrarProduto = new JfCadastrarProduto();
        JfCadastrarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbCadastrarProdutoActionPerformed

    private void JbRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRetornarActionPerformed
        UsuarioLogin JfUsuarioLogin = new UsuarioLogin();
        JfUsuarioLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbRetornarActionPerformed

    private void JbAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarProdutoActionPerformed
        JfAlterarProduto jfAlterarProduto = new JfAlterarProduto();
        jfAlterarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbAlterarProdutoActionPerformed

    private void JbSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSelecionarProdutoActionPerformed
        JfSelecionarProduto jfSelecionarProduto = new JfSelecionarProduto();
        jfSelecionarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbSelecionarProdutoActionPerformed

    private void JbDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDeletarProdutoActionPerformed
        JfDeletarProduto jfDeletarProduto = new JfDeletarProduto();
        jfDeletarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbDeletarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfControleProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfControleProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfControleProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfControleProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfControleProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAlterarProduto;
    private javax.swing.JButton JbCadastrarProduto;
    private javax.swing.JButton JbDeletarProduto;
    private javax.swing.JButton JbRetornar;
    private javax.swing.JButton JbSelecionarProduto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
