/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.produtoGUI;

import control.ControleFuncionario;
import javax.swing.JOptionPane;
import model.Produto;
import view.JfControleProduto;

/**
 *
 * @author Lenovo
 */
public class JfSelecionarProduto extends javax.swing.JFrame {

    /**
     * Creates new form JfSelecionarProduto
     */
    public JfSelecionarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtfIdProduto = new javax.swing.JTextField();
        JbRetornar = new javax.swing.JButton();
        JbSelecionarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Selecionar Produto");

        jLabel2.setText("Identificador");

        JtfIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfIdProdutoActionPerformed(evt);
            }
        });

        JbRetornar.setForeground(new java.awt.Color(255, 0, 0));
        JbRetornar.setText("Retornar");
        JbRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRetornarActionPerformed(evt);
            }
        });

        JbSelecionarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbSelecionarProduto.setText("Selecionar");
        JbSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSelecionarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbRetornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbSelecionarProduto)
                    .addComponent(jLabel2)
                    .addComponent(JtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JbRetornar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbSelecionarProduto)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfIdProdutoActionPerformed

    private void JbRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRetornarActionPerformed
        JfControleProduto JfControleProduto = new JfControleProduto();
        JfControleProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbRetornarActionPerformed

    private void JbSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSelecionarProdutoActionPerformed
        String idProdutoString = JtfIdProduto.getText();
        ControleFuncionario manFuncionario = new ControleFuncionario();
        
        boolean camposPreenchidos = !(idProdutoString.isEmpty());
        if (camposPreenchidos) {
            int idProduto = Integer.parseInt(idProdutoString);
            if(manFuncionario.getProdutoById(idProduto) != null){
                String mensagemSucesso = "Produto: " + manFuncionario.getProdutoById(idProduto).describeProduto() + "\nAcessado com sucesso";
            JOptionPane.showMessageDialog(null, mensagemSucesso);                 
            } else {
                JOptionPane.showMessageDialog(null, "Identificador não encontrado, verifique os dados e tente novamente.");
            }  
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para Selecionar.");
        }
    }//GEN-LAST:event_JbSelecionarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfSelecionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfSelecionarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbRetornar;
    private javax.swing.JButton JbSelecionarProduto;
    private javax.swing.JTextField JtfIdProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
